language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

env:
  matrix:
    - DB=mysql db_dsn='mysql://root@127.0.0.1/cakephp_test'
    - DB=pgsql db_dsn='postgres://postgres@127.0.0.1/cakephp_test'
    - DB=sqlite db_dsn='sqlite:///:memory:'
  global:
    - DEFAULT=1

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: PHPCS=1 DEFAULT=0
    - php: 7.0
      env: PHPSTAN=1 DEFAULT=0
    - php: 7.1
      env: PHPSTAN=1 DEFAULT=0

install:
  - phpenv config-rm xdebug.ini;
  - composer self-update
  - composer install --prefer-dist

before_script:
  - if [[ $PHPSTAN = 1 ]]; then composer require --dev phpstan/phpstan:^0.6; fi

script:
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src; fi
  - if [[ $PHPSTAN = 1 ]]; then vendor/bin/phpstan analyse -l 1 src; fi

notifications:
  email: false
